/*
 * This file is generated by jOOQ.
 */
package com.q3js.jooq.tables.records;


import com.q3js.jooq.tables.PlayerPageVisits;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PlayerPageVisitsRecord extends UpdatableRecordImpl<PlayerPageVisitsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>player_page_visits.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>player_page_visits.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>player_page_visits.player_name</code>.
     */
    public void setPlayerName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>player_page_visits.player_name</code>.
     */
    public String getPlayerName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>player_page_visits.source_ip</code>.
     */
    public void setSourceIp(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>player_page_visits.source_ip</code>.
     */
    public String getSourceIp() {
        return (String) get(2);
    }

    /**
     * Setter for <code>player_page_visits.path</code>.
     */
    public void setPath(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>player_page_visits.path</code>.
     */
    public String getPath() {
        return (String) get(3);
    }

    /**
     * Setter for <code>player_page_visits.user_agent</code>.
     */
    public void setUserAgent(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>player_page_visits.user_agent</code>.
     */
    public String getUserAgent() {
        return (String) get(4);
    }

    /**
     * Setter for <code>player_page_visits.received_at</code>.
     */
    public void setReceivedAt(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>player_page_visits.received_at</code>.
     */
    public OffsetDateTime getReceivedAt() {
        return (OffsetDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlayerPageVisitsRecord
     */
    public PlayerPageVisitsRecord() {
        super(PlayerPageVisits.PLAYER_PAGE_VISITS);
    }

    /**
     * Create a detached, initialised PlayerPageVisitsRecord
     */
    public PlayerPageVisitsRecord(Long id, String playerName, String sourceIp, String path, String userAgent, OffsetDateTime receivedAt) {
        super(PlayerPageVisits.PLAYER_PAGE_VISITS);

        setId(id);
        setPlayerName(playerName);
        setSourceIp(sourceIp);
        setPath(path);
        setUserAgent(userAgent);
        setReceivedAt(receivedAt);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised PlayerPageVisitsRecord
     */
    public PlayerPageVisitsRecord(com.q3js.jooq.tables.pojos.PlayerPageVisits value) {
        super(PlayerPageVisits.PLAYER_PAGE_VISITS);

        if (value != null) {
            setId(value.getId());
            setPlayerName(value.getPlayerName());
            setSourceIp(value.getSourceIp());
            setPath(value.getPath());
            setUserAgent(value.getUserAgent());
            setReceivedAt(value.getReceivedAt());
            resetTouchedOnNotNull();
        }
    }
}
