/*
 * This file is generated by jOOQ.
 */
package com.q3js.jooq.tables.records;


import com.q3js.jooq.tables.SchemaMigrations;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SchemaMigrationsRecord extends UpdatableRecordImpl<SchemaMigrationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>schema_migrations.filename</code>.
     */
    public void setFilename(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>schema_migrations.filename</code>.
     */
    public String getFilename() {
        return (String) get(0);
    }

    /**
     * Setter for <code>schema_migrations.applied_at</code>.
     */
    public void setAppliedAt(OffsetDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>schema_migrations.applied_at</code>.
     */
    public OffsetDateTime getAppliedAt() {
        return (OffsetDateTime) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SchemaMigrationsRecord
     */
    public SchemaMigrationsRecord() {
        super(SchemaMigrations.SCHEMA_MIGRATIONS);
    }

    /**
     * Create a detached, initialised SchemaMigrationsRecord
     */
    public SchemaMigrationsRecord(String filename, OffsetDateTime appliedAt) {
        super(SchemaMigrations.SCHEMA_MIGRATIONS);

        setFilename(filename);
        setAppliedAt(appliedAt);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised SchemaMigrationsRecord
     */
    public SchemaMigrationsRecord(com.q3js.jooq.tables.pojos.SchemaMigrations value) {
        super(SchemaMigrations.SCHEMA_MIGRATIONS);

        if (value != null) {
            setFilename(value.getFilename());
            setAppliedAt(value.getAppliedAt());
            resetTouchedOnNotNull();
        }
    }
}
