packages:
  - website
  - game/client
  - game/server

allowBuilds:
  '@fails-components/webtransport-transport-http3-quiche': true
  esbuild: true
  sharp: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
