// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { getAllServers, getGlobalScoreboard, getKillDistribution, getPlayerStats, ingestEvent, type Options, refreshServer } from '../sdk.gen';
import type { GetAllServersData, GetAllServersResponse, GetGlobalScoreboardData, GetGlobalScoreboardResponse, GetKillDistributionData, GetKillDistributionResponse, GetPlayerStatsData, GetPlayerStatsResponse, IngestEventData, RefreshServerData, RefreshServerResponse } from '../types.gen';

/**
 * Ingest Event
 */
export const ingestEventMutation = (options?: Partial<Options<IngestEventData>>): UseMutationOptions<unknown, DefaultError, Options<IngestEventData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<IngestEventData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ingestEvent({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getKillDistributionQueryKey = (options?: Options<GetKillDistributionData>) => createQueryKey('getKillDistribution', options);

/**
 * Get Kill Distribution
 */
export const getKillDistributionOptions = (options?: Options<GetKillDistributionData>) => queryOptions<GetKillDistributionResponse, DefaultError, GetKillDistributionResponse, ReturnType<typeof getKillDistributionQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getKillDistribution({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getKillDistributionQueryKey(options)
});

export const getPlayerStatsQueryKey = (options: Options<GetPlayerStatsData>) => createQueryKey('getPlayerStats', options);

/**
 * Get Player Stats
 */
export const getPlayerStatsOptions = (options: Options<GetPlayerStatsData>) => queryOptions<GetPlayerStatsResponse, DefaultError, GetPlayerStatsResponse, ReturnType<typeof getPlayerStatsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getPlayerStats({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPlayerStatsQueryKey(options)
});

export const getGlobalScoreboardQueryKey = (options?: Options<GetGlobalScoreboardData>) => createQueryKey('getGlobalScoreboard', options);

/**
 * Get Global Scoreboard
 */
export const getGlobalScoreboardOptions = (options?: Options<GetGlobalScoreboardData>) => queryOptions<GetGlobalScoreboardResponse, DefaultError, GetGlobalScoreboardResponse, ReturnType<typeof getGlobalScoreboardQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getGlobalScoreboard({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getGlobalScoreboardQueryKey(options)
});

export const getAllServersQueryKey = (options?: Options<GetAllServersData>) => createQueryKey('getAllServers', options);

/**
 * Get All Servers
 */
export const getAllServersOptions = (options?: Options<GetAllServersData>) => queryOptions<GetAllServersResponse, DefaultError, GetAllServersResponse, ReturnType<typeof getAllServersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAllServers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAllServersQueryKey(options)
});

/**
 * Refresh Server
 */
export const refreshServerMutation = (options?: Partial<Options<RefreshServerData>>): UseMutationOptions<RefreshServerResponse, DefaultError, Options<RefreshServerData>> => {
    const mutationOptions: UseMutationOptions<RefreshServerResponse, DefaultError, Options<RefreshServerData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await refreshServer({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
