/*
 * This file is generated by jOOQ.
 */
package com.q3js.jooq.tables;


import com.q3js.jooq.DefaultSchema;
import com.q3js.jooq.Indexes;
import com.q3js.jooq.Keys;
import com.q3js.jooq.tables.records.EventsRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Events extends TableImpl<EventsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>events</code>
     */
    public static final Events EVENTS = new Events();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EventsRecord> getRecordType() {
        return EventsRecord.class;
    }

    /**
     * The column <code>events.id</code>.
     */
    public final TableField<EventsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("nextval('events_id_seq1'::regclass)"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>events.source_ip</code>.
     */
    public final TableField<EventsRecord, String> SOURCE_IP = createField(DSL.name("source_ip"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>events.event_type</code>.
     */
    public final TableField<EventsRecord, String> EVENT_TYPE = createField(DSL.name("event_type"), SQLDataType.CLOB.nullable(false).defaultValue(DSL.field(DSL.raw("'unknown'::text"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>events.killer_client_num</code>.
     */
    public final TableField<EventsRecord, Integer> KILLER_CLIENT_NUM = createField(DSL.name("killer_client_num"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>events.killer_name</code>.
     */
    public final TableField<EventsRecord, String> KILLER_NAME = createField(DSL.name("killer_name"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>events.victim_client_num</code>.
     */
    public final TableField<EventsRecord, Integer> VICTIM_CLIENT_NUM = createField(DSL.name("victim_client_num"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>events.victim_name</code>.
     */
    public final TableField<EventsRecord, String> VICTIM_NAME = createField(DSL.name("victim_name"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>events.means_of_death</code>.
     */
    public final TableField<EventsRecord, Integer> MEANS_OF_DEATH = createField(DSL.name("means_of_death"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>events.game_time</code>.
     */
    public final TableField<EventsRecord, Integer> GAME_TIME = createField(DSL.name("game_time"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>events.server_time</code>.
     */
    public final TableField<EventsRecord, Integer> SERVER_TIME = createField(DSL.name("server_time"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>events.map_name</code>.
     */
    public final TableField<EventsRecord, String> MAP_NAME = createField(DSL.name("map_name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>events.received_at</code>.
     */
    public final TableField<EventsRecord, OffsetDateTime> RECEIVED_AT = createField(DSL.name("received_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private Events(Name alias, Table<EventsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Events(Name alias, Table<EventsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>events</code> table reference
     */
    public Events(String alias) {
        this(DSL.name(alias), EVENTS);
    }

    /**
     * Create an aliased <code>events</code> table reference
     */
    public Events(Name alias) {
        this(alias, EVENTS);
    }

    /**
     * Create a <code>events</code> table reference
     */
    public Events() {
        this(DSL.name("events"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_EVENTS_EVENT_TYPE_KILLER_NAME, Indexes.IDX_EVENTS_EVENT_TYPE_RECEIVED_AT, Indexes.IDX_EVENTS_RECEIVED_AT);
    }

    @Override
    public UniqueKey<EventsRecord> getPrimaryKey() {
        return Keys.EVENTS_PKEY1;
    }

    @Override
    public List<Check<EventsRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("chk_events_event_type"), "((event_type = ANY (ARRAY['kill'::text, 'join'::text, 'leave'::text, 'unknown'::text])))", true),
            Internal.createCheck(this, DSL.name("chk_events_payload_shape"), "((((event_type = 'kill'::text) AND (killer_client_num IS NOT NULL) AND (killer_name IS NOT NULL) AND (victim_client_num IS NOT NULL) AND (victim_name IS NOT NULL) AND (means_of_death IS NOT NULL)) OR ((event_type = ANY (ARRAY['join'::text, 'leave'::text])) AND (killer_client_num IS NOT NULL) AND (killer_name IS NOT NULL) AND (victim_client_num IS NULL) AND (victim_name IS NULL) AND (means_of_death IS NULL)) OR (event_type = 'unknown'::text)))", true)
        );
    }

    @Override
    public Events as(String alias) {
        return new Events(DSL.name(alias), this);
    }

    @Override
    public Events as(Name alias) {
        return new Events(alias, this);
    }

    @Override
    public Events as(Table<?> alias) {
        return new Events(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Events rename(String name) {
        return new Events(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Events rename(Name name) {
        return new Events(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Events rename(Table<?> name) {
        return new Events(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Events where(Condition condition) {
        return new Events(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Events where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Events where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Events where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Events where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Events where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Events where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Events where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Events whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Events whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
