/*
 * This file is generated by jOOQ.
 */
package com.q3js.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PlayerPageVisits implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String playerName;
    private String sourceIp;
    private String path;
    private String userAgent;
    private OffsetDateTime receivedAt;

    public PlayerPageVisits() {}

    public PlayerPageVisits(PlayerPageVisits value) {
        this.id = value.id;
        this.playerName = value.playerName;
        this.sourceIp = value.sourceIp;
        this.path = value.path;
        this.userAgent = value.userAgent;
        this.receivedAt = value.receivedAt;
    }

    public PlayerPageVisits(
        Long id,
        String playerName,
        String sourceIp,
        String path,
        String userAgent,
        OffsetDateTime receivedAt
    ) {
        this.id = id;
        this.playerName = playerName;
        this.sourceIp = sourceIp;
        this.path = path;
        this.userAgent = userAgent;
        this.receivedAt = receivedAt;
    }

    /**
     * Getter for <code>player_page_visits.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>player_page_visits.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>player_page_visits.player_name</code>.
     */
    public String getPlayerName() {
        return this.playerName;
    }

    /**
     * Setter for <code>player_page_visits.player_name</code>.
     */
    public void setPlayerName(String playerName) {
        this.playerName = playerName;
    }

    /**
     * Getter for <code>player_page_visits.source_ip</code>.
     */
    public String getSourceIp() {
        return this.sourceIp;
    }

    /**
     * Setter for <code>player_page_visits.source_ip</code>.
     */
    public void setSourceIp(String sourceIp) {
        this.sourceIp = sourceIp;
    }

    /**
     * Getter for <code>player_page_visits.path</code>.
     */
    public String getPath() {
        return this.path;
    }

    /**
     * Setter for <code>player_page_visits.path</code>.
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * Getter for <code>player_page_visits.user_agent</code>.
     */
    public String getUserAgent() {
        return this.userAgent;
    }

    /**
     * Setter for <code>player_page_visits.user_agent</code>.
     */
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent;
    }

    /**
     * Getter for <code>player_page_visits.received_at</code>.
     */
    public OffsetDateTime getReceivedAt() {
        return this.receivedAt;
    }

    /**
     * Setter for <code>player_page_visits.received_at</code>.
     */
    public void setReceivedAt(OffsetDateTime receivedAt) {
        this.receivedAt = receivedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PlayerPageVisits other = (PlayerPageVisits) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.playerName == null) {
            if (other.playerName != null)
                return false;
        }
        else if (!this.playerName.equals(other.playerName))
            return false;
        if (this.sourceIp == null) {
            if (other.sourceIp != null)
                return false;
        }
        else if (!this.sourceIp.equals(other.sourceIp))
            return false;
        if (this.path == null) {
            if (other.path != null)
                return false;
        }
        else if (!this.path.equals(other.path))
            return false;
        if (this.userAgent == null) {
            if (other.userAgent != null)
                return false;
        }
        else if (!this.userAgent.equals(other.userAgent))
            return false;
        if (this.receivedAt == null) {
            if (other.receivedAt != null)
                return false;
        }
        else if (!this.receivedAt.equals(other.receivedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.playerName == null) ? 0 : this.playerName.hashCode());
        result = prime * result + ((this.sourceIp == null) ? 0 : this.sourceIp.hashCode());
        result = prime * result + ((this.path == null) ? 0 : this.path.hashCode());
        result = prime * result + ((this.userAgent == null) ? 0 : this.userAgent.hashCode());
        result = prime * result + ((this.receivedAt == null) ? 0 : this.receivedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PlayerPageVisits (");

        sb.append(id);
        sb.append(", ").append(playerName);
        sb.append(", ").append(sourceIp);
        sb.append(", ").append(path);
        sb.append(", ").append(userAgent);
        sb.append(", ").append(receivedAt);

        sb.append(")");
        return sb.toString();
    }
}
