/*
 * This file is generated by jOOQ.
 */
package com.q3js.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SchemaMigrations implements Serializable {

    private static final long serialVersionUID = 1L;

    private String filename;
    private OffsetDateTime appliedAt;

    public SchemaMigrations() {}

    public SchemaMigrations(SchemaMigrations value) {
        this.filename = value.filename;
        this.appliedAt = value.appliedAt;
    }

    public SchemaMigrations(
        String filename,
        OffsetDateTime appliedAt
    ) {
        this.filename = filename;
        this.appliedAt = appliedAt;
    }

    /**
     * Getter for <code>schema_migrations.filename</code>.
     */
    public String getFilename() {
        return this.filename;
    }

    /**
     * Setter for <code>schema_migrations.filename</code>.
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * Getter for <code>schema_migrations.applied_at</code>.
     */
    public OffsetDateTime getAppliedAt() {
        return this.appliedAt;
    }

    /**
     * Setter for <code>schema_migrations.applied_at</code>.
     */
    public void setAppliedAt(OffsetDateTime appliedAt) {
        this.appliedAt = appliedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final SchemaMigrations other = (SchemaMigrations) obj;
        if (this.filename == null) {
            if (other.filename != null)
                return false;
        }
        else if (!this.filename.equals(other.filename))
            return false;
        if (this.appliedAt == null) {
            if (other.appliedAt != null)
                return false;
        }
        else if (!this.appliedAt.equals(other.appliedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.filename == null) ? 0 : this.filename.hashCode());
        result = prime * result + ((this.appliedAt == null) ? 0 : this.appliedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SchemaMigrations (");

        sb.append(filename);
        sb.append(", ").append(appliedAt);

        sb.append(")");
        return sb.toString();
    }
}
