/*
 * This file is generated by jOOQ.
 */
package com.q3js.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Servers implements Serializable {

    private static final long serialVersionUID = 1L;

    private String host;
    private Integer proxyPort;
    private Integer targetPort;
    private Boolean secure;
    private OffsetDateTime lastHeartbeat;
    private String lastInfoJson;
    private OffsetDateTime lastInfoFetchedAt;

    public Servers() {}

    public Servers(Servers value) {
        this.host = value.host;
        this.proxyPort = value.proxyPort;
        this.targetPort = value.targetPort;
        this.secure = value.secure;
        this.lastHeartbeat = value.lastHeartbeat;
        this.lastInfoJson = value.lastInfoJson;
        this.lastInfoFetchedAt = value.lastInfoFetchedAt;
    }

    public Servers(
        String host,
        Integer proxyPort,
        Integer targetPort,
        Boolean secure,
        OffsetDateTime lastHeartbeat,
        String lastInfoJson,
        OffsetDateTime lastInfoFetchedAt
    ) {
        this.host = host;
        this.proxyPort = proxyPort;
        this.targetPort = targetPort;
        this.secure = secure;
        this.lastHeartbeat = lastHeartbeat;
        this.lastInfoJson = lastInfoJson;
        this.lastInfoFetchedAt = lastInfoFetchedAt;
    }

    /**
     * Getter for <code>servers.host</code>.
     */
    public String getHost() {
        return this.host;
    }

    /**
     * Setter for <code>servers.host</code>.
     */
    public void setHost(String host) {
        this.host = host;
    }

    /**
     * Getter for <code>servers.proxy_port</code>.
     */
    public Integer getProxyPort() {
        return this.proxyPort;
    }

    /**
     * Setter for <code>servers.proxy_port</code>.
     */
    public void setProxyPort(Integer proxyPort) {
        this.proxyPort = proxyPort;
    }

    /**
     * Getter for <code>servers.target_port</code>.
     */
    public Integer getTargetPort() {
        return this.targetPort;
    }

    /**
     * Setter for <code>servers.target_port</code>.
     */
    public void setTargetPort(Integer targetPort) {
        this.targetPort = targetPort;
    }

    /**
     * Getter for <code>servers.secure</code>.
     */
    public Boolean getSecure() {
        return this.secure;
    }

    /**
     * Setter for <code>servers.secure</code>.
     */
    public void setSecure(Boolean secure) {
        this.secure = secure;
    }

    /**
     * Getter for <code>servers.last_heartbeat</code>.
     */
    public OffsetDateTime getLastHeartbeat() {
        return this.lastHeartbeat;
    }

    /**
     * Setter for <code>servers.last_heartbeat</code>.
     */
    public void setLastHeartbeat(OffsetDateTime lastHeartbeat) {
        this.lastHeartbeat = lastHeartbeat;
    }

    /**
     * Getter for <code>servers.last_info_json</code>.
     */
    public String getLastInfoJson() {
        return this.lastInfoJson;
    }

    /**
     * Setter for <code>servers.last_info_json</code>.
     */
    public void setLastInfoJson(String lastInfoJson) {
        this.lastInfoJson = lastInfoJson;
    }

    /**
     * Getter for <code>servers.last_info_fetched_at</code>.
     */
    public OffsetDateTime getLastInfoFetchedAt() {
        return this.lastInfoFetchedAt;
    }

    /**
     * Setter for <code>servers.last_info_fetched_at</code>.
     */
    public void setLastInfoFetchedAt(OffsetDateTime lastInfoFetchedAt) {
        this.lastInfoFetchedAt = lastInfoFetchedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Servers other = (Servers) obj;
        if (this.host == null) {
            if (other.host != null)
                return false;
        }
        else if (!this.host.equals(other.host))
            return false;
        if (this.proxyPort == null) {
            if (other.proxyPort != null)
                return false;
        }
        else if (!this.proxyPort.equals(other.proxyPort))
            return false;
        if (this.targetPort == null) {
            if (other.targetPort != null)
                return false;
        }
        else if (!this.targetPort.equals(other.targetPort))
            return false;
        if (this.secure == null) {
            if (other.secure != null)
                return false;
        }
        else if (!this.secure.equals(other.secure))
            return false;
        if (this.lastHeartbeat == null) {
            if (other.lastHeartbeat != null)
                return false;
        }
        else if (!this.lastHeartbeat.equals(other.lastHeartbeat))
            return false;
        if (this.lastInfoJson == null) {
            if (other.lastInfoJson != null)
                return false;
        }
        else if (!this.lastInfoJson.equals(other.lastInfoJson))
            return false;
        if (this.lastInfoFetchedAt == null) {
            if (other.lastInfoFetchedAt != null)
                return false;
        }
        else if (!this.lastInfoFetchedAt.equals(other.lastInfoFetchedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.host == null) ? 0 : this.host.hashCode());
        result = prime * result + ((this.proxyPort == null) ? 0 : this.proxyPort.hashCode());
        result = prime * result + ((this.targetPort == null) ? 0 : this.targetPort.hashCode());
        result = prime * result + ((this.secure == null) ? 0 : this.secure.hashCode());
        result = prime * result + ((this.lastHeartbeat == null) ? 0 : this.lastHeartbeat.hashCode());
        result = prime * result + ((this.lastInfoJson == null) ? 0 : this.lastInfoJson.hashCode());
        result = prime * result + ((this.lastInfoFetchedAt == null) ? 0 : this.lastInfoFetchedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Servers (");

        sb.append(host);
        sb.append(", ").append(proxyPort);
        sb.append(", ").append(targetPort);
        sb.append(", ").append(secure);
        sb.append(", ").append(lastHeartbeat);
        sb.append(", ").append(lastInfoJson);
        sb.append(", ").append(lastInfoFetchedAt);

        sb.append(")");
        return sb.toString();
    }
}
