// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { getAllPlayers, getAllServers, getPlayerScoreboard, getPlayerScoreboardDistribution, getPlayerStats, getRequesterCountry, ingestEvent, type Options, refreshServer } from '../sdk.gen';
import type { GetAllPlayersData, GetAllPlayersResponse, GetAllServersData, GetAllServersResponse, GetPlayerScoreboardData, GetPlayerScoreboardDistributionData, GetPlayerScoreboardDistributionResponse, GetPlayerScoreboardResponse, GetPlayerStatsData, GetPlayerStatsResponse, GetRequesterCountryData, GetRequesterCountryResponse, IngestEventData, RefreshServerData, RefreshServerResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getRequesterCountryQueryKey = (options?: Options<GetRequesterCountryData>) => createQueryKey('getRequesterCountry', options);

/**
 * Get Requester Country
 */
export const getRequesterCountryOptions = (options?: Options<GetRequesterCountryData>) => queryOptions<GetRequesterCountryResponse, DefaultError, GetRequesterCountryResponse, ReturnType<typeof getRequesterCountryQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRequesterCountry({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRequesterCountryQueryKey(options)
});

/**
 * Ingest Event
 */
export const ingestEventMutation = (options?: Partial<Options<IngestEventData>>): UseMutationOptions<unknown, DefaultError, Options<IngestEventData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<IngestEventData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ingestEvent({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getAllPlayersQueryKey = (options?: Options<GetAllPlayersData>) => createQueryKey('getAllPlayers', options);

/**
 * Get All Players
 */
export const getAllPlayersOptions = (options?: Options<GetAllPlayersData>) => queryOptions<GetAllPlayersResponse, DefaultError, GetAllPlayersResponse, ReturnType<typeof getAllPlayersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAllPlayers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAllPlayersQueryKey(options)
});

export const getPlayerScoreboardQueryKey = (options?: Options<GetPlayerScoreboardData>) => createQueryKey('getPlayerScoreboard', options);

/**
 * Get Player Scoreboard
 */
export const getPlayerScoreboardOptions = (options?: Options<GetPlayerScoreboardData>) => queryOptions<GetPlayerScoreboardResponse, DefaultError, GetPlayerScoreboardResponse, ReturnType<typeof getPlayerScoreboardQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getPlayerScoreboard({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPlayerScoreboardQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const getPlayerScoreboardInfiniteQueryKey = (options?: Options<GetPlayerScoreboardData>): QueryKey<Options<GetPlayerScoreboardData>> => createQueryKey('getPlayerScoreboard', options, true);

/**
 * Get Player Scoreboard
 */
export const getPlayerScoreboardInfiniteOptions = (options?: Options<GetPlayerScoreboardData>) => infiniteQueryOptions<GetPlayerScoreboardResponse, DefaultError, InfiniteData<GetPlayerScoreboardResponse>, QueryKey<Options<GetPlayerScoreboardData>>, number | Pick<QueryKey<Options<GetPlayerScoreboardData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetPlayerScoreboardData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getPlayerScoreboard({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPlayerScoreboardInfiniteQueryKey(options)
});

export const getPlayerScoreboardDistributionQueryKey = (options?: Options<GetPlayerScoreboardDistributionData>) => createQueryKey('getPlayerScoreboardDistribution', options);

/**
 * Get Player Scoreboard Distribution
 */
export const getPlayerScoreboardDistributionOptions = (options?: Options<GetPlayerScoreboardDistributionData>) => queryOptions<GetPlayerScoreboardDistributionResponse, DefaultError, GetPlayerScoreboardDistributionResponse, ReturnType<typeof getPlayerScoreboardDistributionQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getPlayerScoreboardDistribution({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPlayerScoreboardDistributionQueryKey(options)
});

export const getPlayerStatsQueryKey = (options: Options<GetPlayerStatsData>) => createQueryKey('getPlayerStats', options);

/**
 * Get Player Stats
 */
export const getPlayerStatsOptions = (options: Options<GetPlayerStatsData>) => queryOptions<GetPlayerStatsResponse, DefaultError, GetPlayerStatsResponse, ReturnType<typeof getPlayerStatsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getPlayerStats({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPlayerStatsQueryKey(options)
});

export const getAllServersQueryKey = (options?: Options<GetAllServersData>) => createQueryKey('getAllServers', options);

/**
 * Get All Servers
 */
export const getAllServersOptions = (options?: Options<GetAllServersData>) => queryOptions<GetAllServersResponse, DefaultError, GetAllServersResponse, ReturnType<typeof getAllServersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAllServers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAllServersQueryKey(options)
});

/**
 * Refresh Server
 */
export const refreshServerMutation = (options?: Partial<Options<RefreshServerData>>): UseMutationOptions<RefreshServerResponse, DefaultError, Options<RefreshServerData>> => {
    const mutationOptions: UseMutationOptions<RefreshServerResponse, DefaultError, Options<RefreshServerData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await refreshServer({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
