// This file is auto-generated by @hey-api/openapi-ts

import type { GetPlayerStatsResponse } from './types.gen';

const playerStatsResponseSchemaResponseTransformer = (data: any) => {
    if (data.playtimeSeconds) {
        data.playtimeSeconds = BigInt(data.playtimeSeconds.toString());
    }
    return data;
};

export const getPlayerStatsResponseTransformer = async (data: any): Promise<GetPlayerStatsResponse> => {
    data = playerStatsResponseSchemaResponseTransformer(data);
    return data;
};
