// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import { getPlayerStatsResponseTransformer } from './transformers.gen';
import type { GetAllPlayersData, GetAllPlayersResponses, GetAllServersData, GetAllServersResponses, GetPlayerScoreboardData, GetPlayerScoreboardDistributionData, GetPlayerScoreboardDistributionResponses, GetPlayerScoreboardResponses, GetPlayerStatsData, GetPlayerStatsResponses, GetRequesterCountryData, GetRequesterCountryResponses, IngestEventData, IngestEventErrors, IngestEventResponses, RefreshServerData, RefreshServerErrors, RefreshServerResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get Requester Country
 */
export const getRequesterCountry = <ThrowOnError extends boolean = false>(options?: Options<GetRequesterCountryData, ThrowOnError>) => (options?.client ?? client).get<GetRequesterCountryResponses, unknown, ThrowOnError>({ url: '/api/country', ...options });

/**
 * Ingest Event
 */
export const ingestEvent = <ThrowOnError extends boolean = false>(options: Options<IngestEventData, ThrowOnError>) => (options.client ?? client).post<IngestEventResponses, IngestEventErrors, ThrowOnError>({
    url: '/api/events',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get All Players
 */
export const getAllPlayers = <ThrowOnError extends boolean = false>(options?: Options<GetAllPlayersData, ThrowOnError>) => (options?.client ?? client).get<GetAllPlayersResponses, unknown, ThrowOnError>({ url: '/api/players', ...options });

/**
 * Get Player Scoreboard
 */
export const getPlayerScoreboard = <ThrowOnError extends boolean = false>(options?: Options<GetPlayerScoreboardData, ThrowOnError>) => (options?.client ?? client).get<GetPlayerScoreboardResponses, unknown, ThrowOnError>({ url: '/api/players/scoreboard', ...options });

/**
 * Get Player Scoreboard Distribution
 */
export const getPlayerScoreboardDistribution = <ThrowOnError extends boolean = false>(options?: Options<GetPlayerScoreboardDistributionData, ThrowOnError>) => (options?.client ?? client).get<GetPlayerScoreboardDistributionResponses, unknown, ThrowOnError>({ url: '/api/players/scoreboard/distribution', ...options });

/**
 * Get Player Stats
 */
export const getPlayerStats = <ThrowOnError extends boolean = false>(options: Options<GetPlayerStatsData, ThrowOnError>) => (options.client ?? client).get<GetPlayerStatsResponses, unknown, ThrowOnError>({
    responseTransformer: getPlayerStatsResponseTransformer,
    url: '/api/players/{playerName}',
    ...options
});

/**
 * Get All Servers
 */
export const getAllServers = <ThrowOnError extends boolean = false>(options?: Options<GetAllServersData, ThrowOnError>) => (options?.client ?? client).get<GetAllServersResponses, unknown, ThrowOnError>({ url: '/api/servers', ...options });

/**
 * Refresh Server
 */
export const refreshServer = <ThrowOnError extends boolean = false>(options: Options<RefreshServerData, ThrowOnError>) => (options.client ?? client).put<RefreshServerResponses, RefreshServerErrors, ThrowOnError>({
    url: '/api/servers/heartbeat',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
