// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type CreateEventRequest = {
    event?: string;
    player?: EventPlayer;
    killer?: EventPlayer;
    victim?: EventPlayer;
    meansOfDeath?: number;
    gameTime?: number;
    serverTime?: number;
    map?: string;
};

export type EventPlayer = {
    clientNum?: number;
    name?: string;
};

export type HeartbeatRequest = {
    proxyPort?: number;
    targetHost?: string;
    targetPort?: number;
};

export type KillDistributionPointResponse = {
    bucketStart: string;
    kills: number;
};

export type PlayerFavoriteMapResponse = {
    mapName: string;
    kills: number;
};

export type PlayerFavoriteWeaponResponse = {
    meansOfDeath: number;
    weaponName: string;
    kills: number;
};

export type PlayerStatsResponse = {
    playerName: string;
    period: ScoreboardPeriod;
    playtimeSeconds: bigint;
    rank: number | null;
    kills: number;
    deaths: number;
    killDeathRatio: number | null;
    favoriteMap: PlayerFavoriteMapResponse | null;
    favoriteWeapon: PlayerFavoriteWeaponResponse | null;
    weaponBreakdown: Array<PlayerWeaponBreakdownResponse>;
    topVictims: Array<PlayerVersusStatResponse>;
    topNemeses: Array<PlayerVersusStatResponse>;
};

export type PlayerVersusStatResponse = {
    playerName: string;
    kills: number;
};

export type PlayerWeaponBreakdownResponse = {
    meansOfDeath: number;
    weaponName: string;
    kills: number;
};

export type ScoreboardEntryResponse = {
    playerName: string;
    kills: number;
};

export const ScoreboardPeriod = {
    DAILY: 'DAILY',
    WEEKLY: 'WEEKLY',
    MONTHLY: 'MONTHLY',
    ALL_TIME: 'ALL_TIME'
} as const;

export type ScoreboardPeriod = typeof ScoreboardPeriod[keyof typeof ScoreboardPeriod];

export type ServerResponse = {
    id: string;
    sv_hostname: string;
    mapname: string;
    g_gametype: number;
    fraglimit: number;
    timelimit: number;
    sv_maxclients: number;
    g_needpass: number;
    capturelimit?: number;
    version?: string;
    location?: string;
    players: number;
    ping?: number;
    host?: string;
    port?: number;
    challenge?: string;
    sv_maxPing?: number;
    sv_minPing?: number;
    com_gamename?: string;
    com_protocol?: number;
    dmflags?: number;
    sv_privateClients?: number;
    sv_minRate?: number;
    sv_maxRate?: number;
    sv_dlRate?: number;
    sv_floodProtect?: number;
    sv_allowDownload?: number;
    bot_minplayers?: number;
    gamename?: string;
    g_maxGameClients?: number;
    users: Array<ServerUserResponse>;
    proxyPort?: number;
    targetPort?: number;
};

export type ServerUserResponse = {
    score: number;
    ping: number;
    name: string;
};

export type IngestEventData = {
    body: CreateEventRequest;
    path?: never;
    query?: never;
    url: '/api/events';
};

export type IngestEventErrors = {
    /**
     * Bad Request
     */
    400: unknown;
};

export type IngestEventResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type GetKillDistributionData = {
    body?: never;
    path?: never;
    query?: {
        period?: string;
    };
    url: '/api/events/distribution';
};

export type GetKillDistributionResponses = {
    /**
     * OK
     */
    200: Array<KillDistributionPointResponse>;
};

export type GetKillDistributionResponse = GetKillDistributionResponses[keyof GetKillDistributionResponses];

export type GetPlayerStatsData = {
    body?: never;
    path: {
        playerName: string;
    };
    query?: {
        period?: string;
    };
    url: '/api/events/players/{playerName}';
};

export type GetPlayerStatsResponses = {
    /**
     * OK
     */
    200: PlayerStatsResponse;
};

export type GetPlayerStatsResponse = GetPlayerStatsResponses[keyof GetPlayerStatsResponses];

export type GetGlobalScoreboardData = {
    body?: never;
    path?: never;
    query?: {
        period?: string;
    };
    url: '/api/events/scoreboard';
};

export type GetGlobalScoreboardResponses = {
    /**
     * OK
     */
    200: Array<ScoreboardEntryResponse>;
};

export type GetGlobalScoreboardResponse = GetGlobalScoreboardResponses[keyof GetGlobalScoreboardResponses];

export type GetAllServersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/servers';
};

export type GetAllServersResponses = {
    /**
     * OK
     */
    200: Array<ServerResponse>;
};

export type GetAllServersResponse = GetAllServersResponses[keyof GetAllServersResponses];

export type RefreshServerData = {
    body: HeartbeatRequest;
    path?: never;
    query?: never;
    url: '/api/servers/heartbeat';
};

export type RefreshServerErrors = {
    /**
     * Bad Request
     */
    400: unknown;
};

export type RefreshServerResponses = {
    /**
     * No Content
     */
    204: void;
};

export type RefreshServerResponse = RefreshServerResponses[keyof RefreshServerResponses];
