/*
 * This file is generated by jOOQ.
 */
package com.q3js.jooq;


import com.q3js.jooq.tables.Events;
import com.q3js.jooq.tables.Servers;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_EVENTS_EVENT_TYPE_KILLER_NAME = Internal.createIndex(DSL.name("idx_events_event_type_killer_name"), Events.EVENTS, new OrderField[] { Events.EVENTS.EVENT_TYPE, Events.EVENTS.KILLER_NAME }, false);
    public static final Index IDX_EVENTS_EVENT_TYPE_RECEIVED_AT = Internal.createIndex(DSL.name("idx_events_event_type_received_at"), Events.EVENTS, new OrderField[] { Events.EVENTS.EVENT_TYPE, Events.EVENTS.RECEIVED_AT.desc() }, false);
    public static final Index IDX_EVENTS_RECEIVED_AT = Internal.createIndex(DSL.name("idx_events_received_at"), Events.EVENTS, new OrderField[] { Events.EVENTS.RECEIVED_AT.desc() }, false);
    public static final Index IDX_SERVERS_LAST_HEARTBEAT = Internal.createIndex(DSL.name("idx_servers_last_heartbeat"), Servers.SERVERS, new OrderField[] { Servers.SERVERS.LAST_HEARTBEAT.desc() }, false);
}
