/*
 * This file is generated by jOOQ.
 */
package com.q3js.jooq;


import org.jooq.Sequence;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sequences {

    /**
     * The sequence <code>events_id_seq1</code>
     */
    public static final Sequence<Long> EVENTS_ID_SEQ1 = Internal.createSequence("events_id_seq1", DefaultSchema.DEFAULT_SCHEMA, DSL.comment(""), SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
