/*
 * This file is generated by jOOQ.
 */
package com.q3js.jooq;


import com.q3js.jooq.tables.Events;
import com.q3js.jooq.tables.PlayerPageVisits;
import com.q3js.jooq.tables.Servers;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>events</code>.
     */
    public static final Events EVENTS = Events.EVENTS;

    /**
     * The table <code>player_page_visits</code>.
     */
    public static final PlayerPageVisits PLAYER_PAGE_VISITS = PlayerPageVisits.PLAYER_PAGE_VISITS;

    /**
     * The table <code>servers</code>.
     */
    public static final Servers SERVERS = Servers.SERVERS;
}
