quarkus:
  http:
    cors:
      enabled: true
      origins: "http://localhost:3000,http://nohttps.q3js.com,https://nohttps.q3js.com,https://q3js.com,https://next.q3js.com,https://old.q3js.com,https://www.q3js.com"
      methods: "GET,PUT,POST,DELETE,OPTIONS"
      headers: "origin,accept,authorization,content-type,x-requested-with"
      access-control-allow-credentials: true
    proxy:
      proxy-address-forwarding: true
      allow-xForwarded: true
      allow-forwarded: true
    host: 0.0.0.0
  vertx:
    event-loops-pool-size: 24
  thread-pool:
    max-threads: 64

  datasource:
    db-kind: postgresql
    username: ${Q3JS_DB_USER:postgres}
    password: ${Q3JS_DB_PASSWORD:postgres}
    jdbc:
      url: ${Q3JS_DB_URL:jdbc:postgresql://localhost:5432/postgres}
      min-size: 20
      max-size: 120
      acquisition-timeout: 1S
      max-lifetime: 20M
      idle-removal-interval: 2M

  flyway:
    migrate-at-start: true

  jooq:
    dialect: POSTGRES
  native:
    resources:
      includes: dbip-country-lite.mmdb

mp:
  openapi:
    extensions:
      smallrye:
        operationIdStrategy: METHOD

q3js:
  server-info:
    timeout-ms: 3000
  events:
    client-secret: ${Q3JS_EVENT_CLIENT_SECRET:}
  geoip:
    country-db-path: ${Q3JS_COUNTRY_DB_PATH:/data/dbip-country-lite.mmdb}
    country-db-resource: ${Q3JS_COUNTRY_DB_RESOURCE:dbip-country-lite.mmdb}
